2 task
js-tasks-ru/js-20200928_veegres-yerdna pull request #2
Opened 2020-10-02 07:45 UTC by steeerrr

func sortStrings, pick, omit

2020-10-02 07:52 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-03 11:29 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  function compare(a, b) {
данная функция выглядит лишней, ведь мы можем просто передать `collator.compare` в качестве аргумента `sort`

2020-10-03 11:33 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === 'asc' ? resultArr.sort(compare) : resultArr.sort(compare).reverse();
здесь есть логическая проблема. Мы считаем что все что не прошло проверку `param === 'asc'` является сортировкой по `desc`. Похожее логическое заблуждение считать что если животное не является собакой - значит это кошка. Подумайте как избавиться от такой логической проблемы.

Второй момент: при сортировке что по `asc`, что по `desc` сначала происходит сортировка `resultArr.sort(compare)` и только если условие `param === 'asc'` не выполнилось дополнительно вызывается `reverse`.
Подумайте как избавиться от `reverse` и сортировать данные сразу по заданному критерию

2020-10-03 11:34 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (fields.indexOf(key) > -1) {
стоит отдавать предпочтение методу `includes` вместо метода `indexOf`

2020-10-03 11:34 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    if (fields.indexOf(key) === -1) {
стоит отдавать предпочтение методу `includes` вместо метода `indexOf`

2020-10-03 11:34 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    if (fields.indexOf(key) === -1) {
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/includes

2020-10-03 11:34 UTC, dosandk requested changes
необходимо исправить решение `sortStrings`

2020-10-04 09:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-04 10:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-04 15:23 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  console.error('unknown param');
не оставляйте консоли в PR

2020-10-04 15:24 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return resultArr.sort((a, b) => collator.compare(a, b));
строка 11 дублирует строку 13 за исключением последовательности аргументов в `compare`. Попробуйте устранить дублирующийся код

2020-10-04 15:24 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (fields.join().includes(key)) {
`fields.join` - лишняя операция

2020-10-04 15:24 UTC, dosandk approved these changes
решения принимаются, но посмотрите пожалуйста комментарии :mag:

2020-10-04 15:25 UTC, merged